name: Deploy

on:
  push:
    branches:
      - master
  workflow_run:
    workflows: ["Auto Release"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    if: ${{ github.event_name == 'push' || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
          
      - name: Install dependencies
        run: pnpm install
        
      - name: Setup wrangler.toml
        run: |
          cp wrangler.toml.example wrangler.toml
          sed -i 's/your-account-id/${{ secrets.CLOUDFLARE_ACCOUNT_ID }}/g' wrangler.toml
          sed -i 's/your-kv-namespace-id/${{ secrets.CLOUDFLARE_KV_NAMESPACE_ID }}/g' wrangler.toml
          sed -i 's/your-preview-kv-namespace-id/${{ secrets.CLOUDFLARE_KV_PREVIEW_ID }}/g' wrangler.toml
          sed -i 's/generate-an-auth-secret-here/${{ secrets.AUTH_SECRET }}/g' wrangler.toml
        
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}